apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-grafana
  namespace: kube-system
  labels:
    type: nfs
spec:
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    # FIXME: use the right IP
    server: 10.0.0.44
    path: "/var/data/kubernetes"
